### ISSUE TITLE
Comp Complexity of generation algorithm and validation algorithms

### ISSUE THREAD

**Issue by kunxian-xia** [NervosFoundation/binary#6]
In sec 2.1 of the whitepaper, it says "In many specific scenarios, validation algorithms are much more efficient than generation algorithms. The most typical examples are the UTXO transactions and asymmetric cryptographic signatures.". I doubt if this example is correct. 

Actually, to spend a UTXO, one has to generate a valid signature. To verify a transaction, one just verify the signature. However, the runtime needed to verify a ECDSA signature is larger than that of generating a ECDSA signature(according to [Crypto++ 6.0.0 benchmark](https://www.cryptopp.com/benchmarks.html) results).

**Comment by janx** [comment]
@kunxian-xia thanks for pointing this out, asymmetric signature is a bad example indeed. Will fix it.

**Comment by janx** [comment]
fixed by https://github.com/NervosFoundation/rfcs/commit/4257ae956c00b8b9fe05065b622eec2aecb9c4d2
